name: mailto_example
description: Demonstrates how to use the mailto package. Fancy iOS app.
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  mailto:
    path: ../../
  # Most likely, you will want to use the url_launcher in your Flutter app
  # if you are using the mailto package.
  url_launcher: ^5.4.1
  # For a better demo app, not necessary at all
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
